import type { FinancialContext } from '@/lib/ai-context';
import { formatCurrency, formatPercent } from '@/lib/utils';
import { CATEGORY_LABELS } from '@/lib/category-colors';

/**
 * Every string returned here is built directly from computed figures already
 * present in `context` — nothing is generated by a language model. This
 * guarantees the numbers shown to the user are always real (spec §15/§16).
 */
export function generateInsights(context: FinancialContext): string[] {
  const insights: string[] = [];
  const { currency } = context;

  // 1. Budget vs. registered average
  const cmp = context.currentMonth.comparisonToAverage;
  if (context.averageMonthlyBudget > 0) {
    if (cmp.status === 'equal') {
      insights.push(
        `Your ${context.currentMonth.label} budget matches your registered average monthly budget.`
      );
    } else {
      insights.push(
        `Your ${context.currentMonth.label} budget is ${formatPercent(cmp.percent)} ${cmp.status} your registered average budget (${formatCurrency(cmp.absDiff, currency)} ${cmp.status}).`
      );
    }
  }

  // 2. Largest month-over-month category change
  const prevByCategory = new Map(
    context.previousMonth.categoryBreakdown.map((c) => [c.category, c.amount])
  );
  let biggestChange: { category: string; percent: number; direction: 'increased' | 'decreased' } | null = null;

  for (const entry of context.currentMonth.categoryBreakdown) {
    const prevAmount = prevByCategory.get(entry.category) ?? 0;
    if (prevAmount <= 0) continue;
    const percentChange = ((entry.amount - prevAmount) / prevAmount) * 100;
    if (Math.abs(percentChange) < 10) continue; // only surface meaningful shifts
    if (!biggestChange || Math.abs(percentChange) > Math.abs(biggestChange.percent)) {
      biggestChange = {
        category: CATEGORY_LABELS[entry.category],
        percent: Math.round(Math.abs(percentChange) * 10) / 10,
        direction: percentChange > 0 ? 'increased' : 'decreased',
      };
    }
  }
  if (biggestChange) {
    insights.push(
      `Your ${biggestChange.category} expenses ${biggestChange.direction} by ${formatPercent(biggestChange.percent)} compared with ${context.previousMonth.label}.`
    );
  }

  // 3. Highest spending category this month
  if (context.currentMonth.highestCategory) {
    insights.push(
      `${CATEGORY_LABELS[context.currentMonth.highestCategory.category]} was your highest expense category this month at ${formatCurrency(context.currentMonth.highestCategory.amount, currency)}.`
    );
  }

  // 4. Savings & investments this month
  const monthSavingsInvestments = context.currentMonth.totalSavings + context.currentMonth.totalInvestments;
  if (monthSavingsInvestments > 0) {
    insights.push(
      `You allocated ${formatCurrency(monthSavingsInvestments, currency)} toward savings and investments this month.`
    );
  }

  // 5. Budget utilization
  if (context.currentMonth.totalBudget > 0) {
    if (context.currentMonth.utilizationPercent > 100) {
      insights.push(
        `You've exceeded this month's budget by ${formatCurrency(context.currentMonth.totalExpenses - context.currentMonth.totalBudget, currency)}.`
      );
    } else {
      insights.push(
        `You've used ${formatPercent(context.currentMonth.utilizationPercent)} of your available monthly budget.`
      );
    }
  }

  return insights;
}
